### ISSUE TITLE
Plugin is not categorised

### ISSUE THREAD

**Issue by riban-bw** [brummer10/ImpulseLoader.lv2#2]
When building the LV2 there is no category so it will get filtered in the "Other" list of plugins. It should have a catagory that defines how a host lists it, e.g. "Reverb".

**Comment by brummer10** [comment]
Hi
I've put it under the Mixer category, but, that is obsoletely wrong. So I follow your suggestion and put it under the ReverbPlugin Category now. I does the same for the Stereo version. 
Thanks for reporting the issue to me.
